EwuConnect3_0 (It really does get better)/EWUConnect/EWUConnectMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EwuConnect.MVC.Models;

namespace EwuConnect.MVC.Controllers
{
	public class HomeController : Controller
	{
		public IActionResult Home()
		{
			return View();
		}

		public IActionResult About()
		{
			return View();
		}

		public IActionResult Connections()
		{
			return View();
		}

		public IActionResult Search()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

EwuConnect3_0 (It really does get better)/EWUConnect/EWUConnectMVC/Controllers/MentorController.cs
using Microsoft.AspNetCore.Mvc;
using EwuConnect.Domain.Models.MentorViewModel;
using EwuConnect.Domain;

namespace EwuConnect.MVC.Controllers
{

		
	public class MentorController : Controller
	{
		private readonly IEmailSender email_service;

		public MentorController(IEmailSender emailservice)
		{
			email_service = emailservice;
		}


		[HttpGet]
		public IActionResult BecomeMentor()
		{
			return View(new MentorViewModel());
		}
		[HttpPost]
		public IActionResult BecomeMentor(MentorViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				var subject = "EWU CONNECT - GENERAL QUESTION";

				string body = "<b>From:</b> " + viewModel.FirstName + " " + viewModel.LastName + "<br /><br />";
				body += "<b>Email:</b> " + viewModel.Email + "<br /><br />";
				body += "<b>Phone:</b>" + " (" + viewModel.AreaCode + ") - " + viewModel.FirstPhone + " - " + viewModel.LastPhone + "<br /><br />";
				body += "<b>Company/University:</b> " + viewModel.Association + "<br /><br />";
				body += "<b>Major:</b> " + viewModel.Major + "<br /><br />";
				body += "<b>Graduated:</b> " + viewModel.Graduated + "<br /><br />";
				body += "<b>Message:</b> <br />" + viewModel.Comment;

				bool sent = email_service.SendEmailAsync(viewModel.Email, subject, body).Result;
				ModelState.Clear();
				return View(new MentorViewModel { isSent = sent });

			}

			return View(viewModel);
		}
	}

}

EwuConnect3_0 (It really does get better)/EWUConnect/EWUConnectMVC/Views/Home/About.cshtml
@{
	ViewData["Title"] = "About";
}

<asp:Content ID="Content2" ContentPlaceHolderID="LandingPage" runat="server">
	<link href="/css/about.css" rel="stylesheet" type="text/css">

	<div class="container1">

		<div class="bootstrapGrid">
			<div class="row">
				<div class="col-md-12">
					<div id="about">
						The purpose of the program is to establish a relationship in which the Career Mentor can help develop
						the Student Mentee’s professional and personal growth, enhancing networking and decision-making
						skills, as well as offering advice from a “real world” professional’s perspective. The goal of the program
						is to assist students with a successful transition from the life of a college student to the life of a working
						professional.
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<blockquote>
						It has been most interesting speaking with an accountant hands on because I don't know
						anyone family or friend wise who is an accountant. It is nice to be able to ask questions
						and learn about the specifics in all aspects to the accounting field.
					</blockquote>
				</div>
				<div class="col-md-6">
					<blockquote>
						I've found this program to be very helpful! It's awesome to get a professional's advice
						on preparing career materials and a buffer for networking events. I've been highly
						recommending the program to my peers :) <span style="opacity: 0;">This sentence is pad.</span>
					</blockquote>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<blockquote>
						Practice with interviews is very valuable since that isn't really my strong suit. I'm always
						amazed at how many resources (blogs, websites, articles) that Rebecca can find on the topics
						we're focusing on. We've mostly discussed interviewing and then had a mock interview session
						with feedback. Both mentors were involved and they videotaped it so we can see our nervous
						tics, body language, etc.
					</blockquote>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<a asp-controller="Mentor" asp-action="BecomeMentor" class="btn btn-info btn-lg">Become a Mentor</a>
				</div>
			</div>
		</div>
	</div>
</asp:Content>

EwuConnect3_0 (It really does get better)/EWUConnect/EWUConnectMVC/Views/Home/Connections.cshtml
@{
    ViewData["Title"] = "Connections";
}
    <asp:Content ID="Content1" ContentPlaceHolderID="LandingPage" runat="server">
        <link href="/css/connections.css" rel="stylesheet" type="text/css" />

        <div class="container1">
            <div class="bootstrapGrid">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Connections</h1>
                    </div>
                    <div class="col-sm-12">
                        <p>This is where you will view previously made connections and messages.</p>
                    </div>
                </div>
            </div>
        </div>
    </asp:Content>

EwuConnect3_0 (It really does get better)/EWUConnect/EWUConnectMVC/Views/Home/Home.cshtml
@using Microsoft.AspNetCore.Identity
@using EwuConnect.Domain.Models
@inject SignInManager<ApplicationUser> SignInManager

@{
	ViewData["Title"] = "EWU Connect";
}

<asp:Content ID="LandingPage" ContentPlaceHolderID="LandingPage" class="masthead body">
	<link rel="stylesheet" href="/css/index.css" type="text/css" media="screen" />

	<div class="container1">
		<div class="bootstrapGrid">
			<div class="row">
				<div class="col-sm-12">
					<h1 style="font-size: 200%">
						EWU Connect
					</h1>
				</div>
				<div class="col-sm-12">
					<h4>Connecting Real World Skill With Tomorrows Leaders</h4>
				</div>
			</div>
			<div class="row buttons">

				@if (!SignInManager.IsSignedIn(User))
				{
					<div class="col-sm-6">
						<div class="float-right">
							<a asp-controller="Mentor" asp-action="BecomeMentor" class="btn btn-info btn-lg">Become a Mentor</a>

						</div>
					</div>
					<div class="col-sm-6">
						<div class="float-left">
							<a asp-controller="Account" asp-action="Login" class="btn btn-danger btn-lg" Style="background-color: #a10022">EWU SSO Login</a>
						</div>
					</div>
				}
				else
				{
					<div class="col-sm-12">
						<div>
							<a asp-controller="Mentor" asp-action="BecomeMentor" class="btn btn-info btn-lg">Become a Mentor</a>

						</div>
					</div>
				}
			</div>
		</div>
	</div>
</asp:Content>

EwuConnect3_0 (It really does get better)/EWUConnect/EWUConnectMVC/Views/Home/Search.cshtml
@{
    ViewData["Title"] = "Search";
}
    <asp:Content ID="Content1" ContentPlaceHolderID="LandingPage" runat="server">
        <link href="/css/search.css" rel="stylesheet" type="text/css" />

        <div class="container1">
            <div class="bootstrapGrid">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Search</h1>
                    </div>
                    <div class="col-sm-12">
                        <p>This is where you will search for mentors.</p>
                    </div>
                </div>
            </div>
        </div>
    </asp:Content>