EWUConnect/EWUConnectMVC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EwuConnect.Domain.Models.ContactViewModel;
using System.Net.Mail;
using System.Net;
using EwuConnect.Domain;

namespace EwuConnect.MVC.Controllers
{
	public class ContactController : Controller
	{
		private readonly IEmailSender email_service;

		public ContactController(IEmailSender emailService)
		{
			email_service = emailService;
		}


		[HttpGet]
		public IActionResult Index()
		{
			return View(new ContactViewModel());
		}
		[HttpPost]
		public IActionResult Index(ContactViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				var subject = "EWU CONNECT - GENERAL QUESTION";

				string body = "<b>From:</b> " + viewModel.FirstName + " " + viewModel.LastName + "<br /><br />";
				body += "<b>Email:</b> " + viewModel.Email + "<br /><br />";
				body += "<b>Question:</b> <br />" + viewModel.Comment;

				bool sent = email_service.SendEmailAsync(viewModel.Email, subject, body).Result;
				ModelState.Clear();
				return View(new ContactViewModel { isSent = sent });
									
			}
			
			return View(viewModel);
		}
	}
}

EWUConnect/EWUConnectMVC/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EwuConnect.Domain;
using EwuConnect.Domain.Models.Forums;
using EwuConnect.Domain.Models.Posts;
using EwuConnect.Domain.Models.Forums.ViewModels;
using EwuConnect.Domain.Models.Posts.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace EwuConnect.MVC.Controllers
{
    public class ForumController : Controller
    {
		private readonly IForum forum_Service;
		private readonly IPost post_Service;
		public ForumController(IForum forumService)
		{
			forum_Service = forumService;
		}

		public IActionResult Index()
		{
			var forums = forum_Service.GetAll()
				.Select(forum => new ForumListingModel {
					Id = forum.Id,
					Name = forum.Title,
					Description = forum.Description
				});

			var model = new ForumIndexModel
			{
				ForumList = forums
			};
            return View(model);
        }
		public IActionResult Topic(int id)
		{
			var forum = forum_Service.GetById(id);
			var posts = forum.Posts;

			var postListings = posts.Select(post => new PostListingModel
			{
				Id = post.Id,
				AuthorId = post.User.Id,
				Author = post.User.UserName,
				Title = post.Title,
				DatePosted = post.Created.ToString(),
				RepliesCount = post.Replies.Count(),
				Forum = BuildForumListing(post)
			});

			var model = new ForumTopicModel
			{
				Posts = postListings,
				Forum = BuildForumListing(forum)
			};

			return View(model);
		}

		private ForumListingModel BuildForumListing(Post post)
		{
			var forum = post.Forum;

			return BuildForumListing(forum);
		}
		private ForumListingModel BuildForumListing(Forum forum)
		{
			return new ForumListingModel
			{
				Id = forum.Id,
				Name = forum.Title,
				Description = forum.Description,
				ImageUrl = forum.ImageUrl
			};
		}
	}
}

EWUConnect/EWUConnectMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>EWU Connect</title>

	<!-- Bootstrap core CSS -->
	<link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

	<link href="/css/master.css" rel="stylesheet" />

	<asp:ContentPlaceHolder ID="head" runat="server" />
</head>

<body class="d-flex flex-column">
	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
		<div class="container">
					<a asp-controller="Home" asp-action="Index" class="nav-link">EWU Connect</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Home" asp-action="Connections" class="nav-link">Connections</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Home" asp-action="Search" class="nav-link">Search</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Forum" asp-action="Index" class="nav-link">Forums</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Home" asp-action="About" class="nav-link">About</a>
						</li>
						<li class="nav-item">
							<a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
						</li>

					</ul>
					@await Html.PartialAsync("_LoginPartial")
				</div>
		</div>
	</nav>

	<partial name="_CookieConsentPartial" />
	<!-- End Navigation -->


	<div class="footer fixed-bottom text-white">
		<p>Copyright &copy; EWU Connect — Jessica Jahn, Kyle Burgi, and Alex Toenniessen</p>
	</div>
	@RenderBody()

	<!-- Bootstrap core JavaScript -->
	<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
	<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
	<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js"></script>

	@RenderSection("Scripts", required: false)


</body>
</html>